name: Upload Python Package

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - ".github/workflows/*"

permissions:
  contents: read

jobs:
  publish:

    runs-on: ubuntu-latest
    environment:
      name: testpypi

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: python -m build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
          repository-url: https://test.pypi.org/legacy/
          password: ${{ secrets.PYPI_API_TOKEN }}